#!/bin/sh
#    SQUID Acconting                                            [SAcc system] 
#   Copyright (C) 2003  the.Virus
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
_date=`date +%y%m%d`
/usr/local/bin/mysqldump --default-character-set=koi8r sacc >/tmp/backup.sql
bzip2 /tmp/backup.sql
mv /tmp/backup.sql.bz2 /usr/local/sacc/addons/backup/data/$_date.bz2
